-- 003_recuperacion_contrasena.sql
--
-- Tabla para el "¿Olvidaste tu contraseña?" del portal.
--
-- NO AFECTA AL PANEL DE ADMINISTRACIÓN. Es una tabla nueva, nadie más la
-- lee ni la escribe, y ninguna tabla existente cambia. Igual hay que
-- correr `python database/migrar.py` después del pull, porque si la tabla
-- no está, la pantalla de recuperar contraseña falla.
--
-- Por qué hace falta una tabla y no alcanza con un campo en usuario:
-- un pedido de recuperación es un hecho con fecha, vencimiento y un solo
-- uso. Guardarlo en usuario obligaría a agregar tres columnas que casi
-- siempre están vacías y a borrarlas a mano después.

CREATE TABLE recuperacion_contrasena (
    id_recuperacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario integer NOT NULL,
    -- No se guarda el token, se guarda su huella SHA-256. Si alguien lee
    -- esta tabla no puede armar el enlace: la huella no se puede volver
    -- atrás. Es el mismo criterio que se usa con las contraseñas.
    token_hash varchar(64) NOT NULL,
    fecha_creacion timestamp NOT NULL DEFAULT now(),
    fecha_expiracion timestamp NOT NULL,
    -- Nula mientras el enlace no se usó. Al usarse se sella con la fecha,
    -- y así el mismo enlace no sirve dos veces.
    fecha_uso timestamp,
    CONSTRAINT fk_recuperacion_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario),
    CONSTRAINT uq_recuperacion_token UNIQUE (token_hash),
    CONSTRAINT ck_recuperacion_vigencia
        CHECK (fecha_expiracion > fecha_creacion)
);

-- Para buscar los pedidos abiertos de una persona al invalidarlos.
CREATE INDEX idx_recuperacion_usuario
    ON recuperacion_contrasena (id_usuario, fecha_uso);
