-- Estructura de PostgreSQL del prototipo.
-- Tablas, columnas, nulos, PK, FK, UK y catálogos: documentación del modelo de datos.
-- der.txt describe otro modelo (otras tablas y columnas) y no se mezcla con este script.
-- id_tipo_sangre en usuario es nulo: lo asigna el laboratorio (cardinalidad del diccionario y DER).
-- No se crean columnas que solo aparecen en una regla o solo en el DER
-- (vigente, cupo_donacion, tipo_donacion, leido, nivel_visibilidad).

BEGIN;

CREATE TABLE rol (
    id_rol integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(30) NOT NULL,
    nombre varchar(80) NOT NULL,
    CONSTRAINT uq_rol_codigo UNIQUE (codigo),
    CONSTRAINT ck_rol_codigo CHECK (codigo IN ('DONANTE', 'ENFERMERIA', 'JEFATURA', 'ADMIN'))
);

CREATE TABLE tipo_sangre (
    id_tipo_sangre integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo char(2) NOT NULL,
    factor char(1) NOT NULL,
    CONSTRAINT uq_tipo_sangre_grupo_factor UNIQUE (grupo, factor),
    CONSTRAINT ck_tipo_sangre_grupo CHECK (grupo IN ('A', 'B', 'AB', 'O')),
    CONSTRAINT ck_tipo_sangre_factor CHECK (factor IN ('+', '-'))
);

CREATE TABLE usuario (
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento varchar(20) NOT NULL,
    nombre varchar(80) NOT NULL,
    apellido varchar(80) NOT NULL,
    fecha_nacimiento date NOT NULL,
    genero varchar(20) NOT NULL,
    contrasena varchar(255),
    consentimiento_privacidad boolean NOT NULL,
    estado boolean NOT NULL DEFAULT true,
    cuenta_suprimida boolean NOT NULL DEFAULT false,
    fecha_alta timestamp NOT NULL,
    id_tipo_sangre integer,
    CONSTRAINT uq_usuario_documento UNIQUE (documento),
    CONSTRAINT ck_usuario_genero CHECK (genero IN ('Masculino', 'Femenino')),
    CONSTRAINT ck_usuario_supresion CHECK (cuenta_suprimida = false OR contrasena IS NULL),
    CONSTRAINT fk_usuario_tipo_sangre FOREIGN KEY (id_tipo_sangre) REFERENCES tipo_sangre (id_tipo_sangre)
);

CREATE TABLE usuario_rol (
    id_usuario integer NOT NULL,
    id_rol integer NOT NULL,
    CONSTRAINT pk_usuario_rol PRIMARY KEY (id_usuario, id_rol),
    CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_usuario_rol_rol FOREIGN KEY (id_rol) REFERENCES rol (id_rol)
);

CREATE TABLE perfil_personal (
    id_perfil_personal integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario integer NOT NULL,
    registro_profesional varchar(30) NOT NULL,
    correo_institucional varchar(120) NOT NULL,
    fecha_alta_servicio date,
    CONSTRAINT uq_perfil_personal_usuario UNIQUE (id_usuario),
    CONSTRAINT uq_perfil_personal_registro UNIQUE (registro_profesional),
    CONSTRAINT uq_perfil_personal_correo UNIQUE (correo_institucional),
    CONSTRAINT fk_perfil_personal_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario)
);

CREATE TABLE telefono (
    id_telefono integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario integer NOT NULL,
    numero varchar(30) NOT NULL,
    es_principal boolean NOT NULL,
    CONSTRAINT fk_telefono_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario)
);

CREATE TABLE correo (
    id_correo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario integer NOT NULL,
    direccion varchar(120) NOT NULL,
    es_principal boolean NOT NULL,
    CONSTRAINT uq_correo_direccion UNIQUE (direccion),
    CONSTRAINT fk_correo_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario)
);

CREATE TABLE compatibilidad_abo_rh (
    id_compatibilidad integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_donante integer NOT NULL,
    id_tipo_receptor integer NOT NULL,
    CONSTRAINT fk_compatibilidad_donante FOREIGN KEY (id_tipo_donante) REFERENCES tipo_sangre (id_tipo_sangre),
    CONSTRAINT fk_compatibilidad_receptor FOREIGN KEY (id_tipo_receptor) REFERENCES tipo_sangre (id_tipo_sangre)
);

CREATE TABLE solicitud (
    id_solicitud integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitante integer NOT NULL,
    medico_tratante varchar(120),
    id_tipo_sangre integer NOT NULL,
    unidades_requeridas integer NOT NULL,
    unidades_asignadas integer NOT NULL,
    consentimiento_publicacion boolean NOT NULL,
    fecha_limite date,
    estado varchar(20) NOT NULL,
    fecha_creacion timestamp NOT NULL,
    CONSTRAINT fk_solicitud_solicitante FOREIGN KEY (id_solicitante) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_solicitud_tipo_sangre FOREIGN KEY (id_tipo_sangre) REFERENCES tipo_sangre (id_tipo_sangre),
    CONSTRAINT ck_solicitud_unidades CHECK (
        unidades_requeridas > 0
        AND unidades_asignadas >= 0
        AND unidades_asignadas <= unidades_requeridas
    ),
    CONSTRAINT ck_solicitud_estado CHECK (estado IN ('Publicada', 'Completa', 'Vencida', 'Revocada')),
    CONSTRAINT ck_solicitud_publicacion CHECK (estado <> 'Publicada' OR consentimiento_publicacion)
);

CREATE TABLE horario_disponible (
    id_horario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_semana varchar(15) NOT NULL,
    hora_inicio time NOT NULL,
    hora_fin time NOT NULL,
    cupo_atencion integer NOT NULL,
    cupo_consejeria integer NOT NULL,
    disponible boolean NOT NULL,
    CONSTRAINT ck_horario_horas CHECK (hora_fin > hora_inicio),
    CONSTRAINT ck_horario_cupos CHECK (cupo_atencion >= 0 AND cupo_consejeria >= 0)
);

CREATE TABLE cita (
    id_cita integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_cita varchar(30) NOT NULL,
    id_usuario integer NOT NULL,
    id_solicitud integer,
    id_personal integer NOT NULL,
    id_horario integer NOT NULL,
    fecha_hora_creacion timestamp NOT NULL,
    estado varchar(20) NOT NULL,
    CONSTRAINT fk_cita_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_cita_solicitud FOREIGN KEY (id_solicitud) REFERENCES solicitud (id_solicitud),
    CONSTRAINT fk_cita_personal FOREIGN KEY (id_personal) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_cita_horario FOREIGN KEY (id_horario) REFERENCES horario_disponible (id_horario),
    CONSTRAINT ck_cita_tipo CHECK (tipo_cita IN (
        'Donacion altruista',
        'Reposicion',
        'Donacion solidaria',
        'Extraccion de compatibilidad'
    )),
    CONSTRAINT ck_cita_estado CHECK (estado IN (
        'Pendiente',
        'Confirmada',
        'Cancelada',
        'Ausente',
        'Completada',
        'No apto'
    ))
);

CREATE TABLE pregunta (
    id_pregunta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parte char(1) NOT NULL,
    enunciado text NOT NULL,
    preselecciona_exclusion boolean NOT NULL,
    CONSTRAINT ck_pregunta_parte CHECK (parte IN ('A', 'B'))
);

CREATE TABLE cuestionario (
    id_cuestionario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cita integer NOT NULL,
    id_pregunta integer NOT NULL,
    id_donante integer NOT NULL,
    id_personal integer,
    valor varchar(255) NOT NULL,
    fecha timestamp NOT NULL,
    CONSTRAINT uq_cuestionario_cita_pregunta UNIQUE (id_cita, id_pregunta),
    CONSTRAINT fk_cuestionario_cita FOREIGN KEY (id_cita) REFERENCES cita (id_cita),
    CONSTRAINT fk_cuestionario_pregunta FOREIGN KEY (id_pregunta) REFERENCES pregunta (id_pregunta),
    CONSTRAINT fk_cuestionario_donante FOREIGN KEY (id_donante) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_cuestionario_personal FOREIGN KEY (id_personal) REFERENCES usuario (id_usuario)
);

CREATE TABLE tipo_medicion (
    id_tipo_medicion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(30) NOT NULL,
    nombre varchar(80) NOT NULL,
    unidad varchar(20) NOT NULL,
    valor_minimo numeric NOT NULL,
    valor_maximo numeric NOT NULL,
    CONSTRAINT uq_tipo_medicion_codigo UNIQUE (codigo),
    CONSTRAINT ck_tipo_medicion_codigo CHECK (codigo IN ('TEMPERATURA', 'PESO', 'PAS', 'PAD', 'HB'))
);

CREATE TABLE medicion (
    id_medicion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cita integer NOT NULL,
    id_personal integer NOT NULL,
    id_tipo_medicion integer NOT NULL,
    valor numeric NOT NULL,
    apto boolean NOT NULL,
    observaciones text,
    fecha timestamp NOT NULL,
    CONSTRAINT uq_medicion_cita_tipo UNIQUE (id_cita, id_tipo_medicion),
    CONSTRAINT fk_medicion_cita FOREIGN KEY (id_cita) REFERENCES cita (id_cita),
    CONSTRAINT fk_medicion_personal FOREIGN KEY (id_personal) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_medicion_tipo FOREIGN KEY (id_tipo_medicion) REFERENCES tipo_medicion (id_tipo_medicion)
);

CREATE TABLE diferimiento (
    id_diferimiento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(120) NOT NULL,
    tipo varchar(20) NOT NULL,
    dias_rehabilitacion integer,
    CONSTRAINT uq_diferimiento_nombre UNIQUE (nombre),
    CONSTRAINT ck_diferimiento_tipo CHECK (tipo IN ('Temporal', 'Permanente')),
    CONSTRAINT ck_diferimiento_dias CHECK (
        (tipo = 'Permanente' AND dias_rehabilitacion IS NULL)
        OR (tipo = 'Temporal' AND dias_rehabilitacion IS NOT NULL AND dias_rehabilitacion >= 0)
    )
);

CREATE TABLE registro_diferimiento (
    id_registro integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_donante integer NOT NULL,
    id_diferimiento integer NOT NULL,
    id_cita integer,
    id_personal integer,
    origen varchar(30) NOT NULL,
    institucion_diagnostico varchar(120) NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date,
    CONSTRAINT fk_registro_donante FOREIGN KEY (id_donante) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_registro_diferimiento FOREIGN KEY (id_diferimiento) REFERENCES diferimiento (id_diferimiento),
    CONSTRAINT fk_registro_cita FOREIGN KEY (id_cita) REFERENCES cita (id_cita),
    CONSTRAINT fk_registro_personal FOREIGN KEY (id_personal) REFERENCES usuario (id_usuario),
    CONSTRAINT ck_registro_origen CHECK (origen IN (
        'CUESTIONARIO_SISTEMA',
        'CUESTIONARIO_PERSONAL',
        'MEDICION',
        'LABORATORIO'
    ))
);

CREATE TABLE extraccion (
    id_extraccion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cita integer NOT NULL,
    id_personal integer NOT NULL,
    codigo_unico varchar(40) NOT NULL,
    fecha timestamp NOT NULL,
    observacion text NOT NULL,
    CONSTRAINT uq_extraccion_cita UNIQUE (id_cita),
    CONSTRAINT uq_extraccion_codigo UNIQUE (codigo_unico),
    CONSTRAINT fk_extraccion_cita FOREIGN KEY (id_cita) REFERENCES cita (id_cita),
    CONSTRAINT fk_extraccion_personal FOREIGN KEY (id_personal) REFERENCES usuario (id_usuario)
);

CREATE TABLE unidad (
    id_unidad integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_extraccion integer NOT NULL,
    id_donante integer NOT NULL,
    id_solicitud integer,
    codigo varchar(40) NOT NULL,
    id_tipo_sangre integer,
    componente varchar(20) NOT NULL DEFAULT 'sangre_total',
    estado varchar(20) NOT NULL,
    fecha_vencimiento date,
    CONSTRAINT uq_unidad_extraccion UNIQUE (id_extraccion),
    CONSTRAINT uq_unidad_codigo UNIQUE (codigo),
    CONSTRAINT fk_unidad_extraccion FOREIGN KEY (id_extraccion) REFERENCES extraccion (id_extraccion),
    CONSTRAINT fk_unidad_donante FOREIGN KEY (id_donante) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_unidad_solicitud FOREIGN KEY (id_solicitud) REFERENCES solicitud (id_solicitud),
    CONSTRAINT fk_unidad_tipo_sangre FOREIGN KEY (id_tipo_sangre) REFERENCES tipo_sangre (id_tipo_sangre),
    CONSTRAINT ck_unidad_componente CHECK (componente = 'sangre_total'),
    CONSTRAINT ck_unidad_estado CHECK (estado IN (
        'Registrada',
        'En laboratorio',
        'En stock',
        'Asignada',
        'Utilizada',
        'Descartada',
        'Vencida'
    ))
);

CREATE TABLE transicion_estado (
    id_transicion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad integer NOT NULL,
    id_personal integer NOT NULL,
    estado_origen varchar(20) NOT NULL,
    estado_destino varchar(20) NOT NULL,
    motivo text,
    fecha timestamp NOT NULL,
    CONSTRAINT fk_transicion_unidad FOREIGN KEY (id_unidad) REFERENCES unidad (id_unidad),
    CONSTRAINT fk_transicion_personal FOREIGN KEY (id_personal) REFERENCES usuario (id_usuario),
    CONSTRAINT ck_transicion_motivo_descarte CHECK (estado_destino <> 'Descartada' OR motivo IS NOT NULL)
);

CREATE TABLE resultado_laboratorio (
    id_resultado integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad integer NOT NULL,
    id_diferimiento integer,
    id_registro_diferimiento integer,
    id_tipo_sangre integer NOT NULL,
    resultado varchar(20) NOT NULL,
    fecha timestamp NOT NULL,
    CONSTRAINT uq_resultado_unidad UNIQUE (id_unidad),
    CONSTRAINT fk_resultado_unidad FOREIGN KEY (id_unidad) REFERENCES unidad (id_unidad),
    CONSTRAINT fk_resultado_diferimiento FOREIGN KEY (id_diferimiento) REFERENCES diferimiento (id_diferimiento),
    CONSTRAINT fk_resultado_registro FOREIGN KEY (id_registro_diferimiento) REFERENCES registro_diferimiento (id_registro),
    CONSTRAINT fk_resultado_tipo_sangre FOREIGN KEY (id_tipo_sangre) REFERENCES tipo_sangre (id_tipo_sangre),
    CONSTRAINT ck_resultado_valor CHECK (resultado IN ('No reactivo', 'Reactivo'))
);

CREATE TABLE asignacion (
    id_asignacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad integer NOT NULL,
    id_solicitud integer NOT NULL,
    fecha timestamp NOT NULL,
    CONSTRAINT uq_asignacion_unidad UNIQUE (id_unidad),
    CONSTRAINT fk_asignacion_unidad FOREIGN KEY (id_unidad) REFERENCES unidad (id_unidad),
    CONSTRAINT fk_asignacion_solicitud FOREIGN KEY (id_solicitud) REFERENCES solicitud (id_solicitud)
);

CREATE TABLE citacion_consejeria (
    id_citacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_donante integer NOT NULL,
    id_personal integer NOT NULL,
    id_horario integer NOT NULL,
    id_resultado integer NOT NULL,
    fecha_hora timestamp,
    estado varchar(20) NOT NULL,
    observaciones text,
    CONSTRAINT uq_citacion_resultado UNIQUE (id_resultado),
    CONSTRAINT fk_citacion_donante FOREIGN KEY (id_donante) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_citacion_personal FOREIGN KEY (id_personal) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_citacion_horario FOREIGN KEY (id_horario) REFERENCES horario_disponible (id_horario),
    CONSTRAINT fk_citacion_resultado FOREIGN KEY (id_resultado) REFERENCES resultado_laboratorio (id_resultado),
    CONSTRAINT ck_citacion_estado CHECK (estado IN ('Pendiente', 'Realizada', 'Ausente'))
);

CREATE TABLE derivacion (
    id_derivacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_registro_diferimiento integer NOT NULL,
    id_personal integer NOT NULL,
    establecimiento_destino varchar(120) NOT NULL,
    fecha date NOT NULL,
    motivo_interno text,
    CONSTRAINT uq_derivacion_registro UNIQUE (id_registro_diferimiento),
    CONSTRAINT fk_derivacion_registro FOREIGN KEY (id_registro_diferimiento) REFERENCES registro_diferimiento (id_registro),
    CONSTRAINT fk_derivacion_personal FOREIGN KEY (id_personal) REFERENCES usuario (id_usuario)
);

CREATE TABLE notificacion (
    id_notificacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario integer NOT NULL,
    id_cita integer,
    id_citacion integer,
    id_solicitud integer,
    tipo varchar(40) NOT NULL,
    mensaje text NOT NULL,
    fecha_envio timestamp NOT NULL,
    CONSTRAINT fk_notificacion_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_notificacion_cita FOREIGN KEY (id_cita) REFERENCES cita (id_cita),
    CONSTRAINT fk_notificacion_citacion FOREIGN KEY (id_citacion) REFERENCES citacion_consejeria (id_citacion),
    CONSTRAINT fk_notificacion_solicitud FOREIGN KEY (id_solicitud) REFERENCES solicitud (id_solicitud),
    CONSTRAINT ck_notificacion_tipo CHECK (tipo IN (
        'CONFIRMACION_CITA',
        'RECORDATORIO_CITA',
        'HABILITACION',
        'AGRADECIMIENTO',
        'ASIGNACION_DONANTE',
        'ASIGNACION_SOLICITANTE',
        'META_COMPLETA',
        'CITACION_GENERICA'
    ))
);

CREATE TABLE contenido_portal (
    id_contenido integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo varchar(200) NOT NULL,
    cuerpo text NOT NULL,
    vigente boolean NOT NULL
);

CREATE TABLE buzon (
    id_mensaje integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario integer NOT NULL,
    mensaje text NOT NULL,
    fecha timestamp NOT NULL,
    CONSTRAINT fk_buzon_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario)
);

CREATE TABLE auditoria (
    id_auditoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario integer NOT NULL,
    entidad varchar(40) NOT NULL,
    id_entidad integer NOT NULL,
    accion varchar(30) NOT NULL,
    fecha timestamp NOT NULL,
    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario),
    CONSTRAINT ck_auditoria_accion CHECK (accion IN (
        'ALTA',
        'MODIFICACION',
        'BAJA',
        'LOGIN',
        'CAMBIO_ESTADO',
        'SUPRESION_CUENTA'
    ))
);

-- Un principal por usuario (RI04).
CREATE UNIQUE INDEX uq_telefono_principal
    ON telefono (id_usuario)
    WHERE es_principal;

CREATE UNIQUE INDEX uq_correo_principal
    ON correo (id_usuario)
    WHERE es_principal;

CREATE INDEX idx_usuario_tipo_sangre ON usuario (id_tipo_sangre);
CREATE INDEX idx_telefono_usuario ON telefono (id_usuario);
CREATE INDEX idx_correo_usuario ON correo (id_usuario);
CREATE INDEX idx_compatibilidad_donante ON compatibilidad_abo_rh (id_tipo_donante);
CREATE INDEX idx_compatibilidad_receptor ON compatibilidad_abo_rh (id_tipo_receptor);
CREATE INDEX idx_solicitud_solicitante ON solicitud (id_solicitante);
CREATE INDEX idx_solicitud_tipo_sangre ON solicitud (id_tipo_sangre);
CREATE INDEX idx_cita_usuario ON cita (id_usuario);
CREATE INDEX idx_cita_solicitud ON cita (id_solicitud);
CREATE INDEX idx_cita_personal ON cita (id_personal);
CREATE INDEX idx_cita_horario ON cita (id_horario);
CREATE INDEX idx_cuestionario_pregunta ON cuestionario (id_pregunta);
CREATE INDEX idx_cuestionario_donante ON cuestionario (id_donante);
CREATE INDEX idx_cuestionario_personal ON cuestionario (id_personal);
CREATE INDEX idx_medicion_cita ON medicion (id_cita);
CREATE INDEX idx_medicion_personal ON medicion (id_personal);
CREATE INDEX idx_registro_donante ON registro_diferimiento (id_donante);
CREATE INDEX idx_registro_diferimiento_causa ON registro_diferimiento (id_diferimiento);
CREATE INDEX idx_registro_cita ON registro_diferimiento (id_cita);
CREATE INDEX idx_registro_personal ON registro_diferimiento (id_personal);
CREATE INDEX idx_extraccion_personal ON extraccion (id_personal);
CREATE INDEX idx_unidad_donante ON unidad (id_donante);
CREATE INDEX idx_unidad_solicitud ON unidad (id_solicitud);
CREATE INDEX idx_unidad_tipo_sangre ON unidad (id_tipo_sangre);
CREATE INDEX idx_transicion_unidad ON transicion_estado (id_unidad);
CREATE INDEX idx_transicion_personal ON transicion_estado (id_personal);
CREATE INDEX idx_resultado_diferimiento ON resultado_laboratorio (id_diferimiento);
CREATE INDEX idx_resultado_registro ON resultado_laboratorio (id_registro_diferimiento);
CREATE INDEX idx_resultado_tipo_sangre ON resultado_laboratorio (id_tipo_sangre);
CREATE INDEX idx_asignacion_solicitud ON asignacion (id_solicitud);
CREATE INDEX idx_citacion_donante ON citacion_consejeria (id_donante);
CREATE INDEX idx_citacion_personal ON citacion_consejeria (id_personal);
CREATE INDEX idx_citacion_horario ON citacion_consejeria (id_horario);
CREATE INDEX idx_derivacion_personal ON derivacion (id_personal);
CREATE INDEX idx_notificacion_usuario ON notificacion (id_usuario);
CREATE INDEX idx_notificacion_cita ON notificacion (id_cita);
CREATE INDEX idx_notificacion_citacion ON notificacion (id_citacion);
CREATE INDEX idx_notificacion_solicitud ON notificacion (id_solicitud);
CREATE INDEX idx_buzon_usuario ON buzon (id_usuario);
CREATE INDEX idx_auditoria_usuario ON auditoria (id_usuario);

-- RN01: apto se calcula con los umbrales del tipo. El personal no lo edita.
CREATE FUNCTION fn_medicion_apto()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_min numeric;
    v_max numeric;
BEGIN
    SELECT valor_minimo, valor_maximo
    INTO v_min, v_max
    FROM tipo_medicion
    WHERE id_tipo_medicion = NEW.id_tipo_medicion;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Tipo de medicion inexistente';
    END IF;

    NEW.apto := NEW.valor >= v_min AND NEW.valor <= v_max;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_medicion_apto
BEFORE INSERT OR UPDATE ON medicion
FOR EACH ROW
EXECUTE FUNCTION fn_medicion_apto();

-- RN02: nadie se valida a si mismo.
CREATE FUNCTION fn_medicion_no_autovalida()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM cita
        WHERE id_cita = NEW.id_cita
          AND id_usuario = NEW.id_personal
    ) THEN
        RAISE EXCEPTION 'El personal no puede validar su propia donacion';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_medicion_no_autovalida
BEFORE INSERT OR UPDATE ON medicion
FOR EACH ROW
EXECUTE FUNCTION fn_medicion_no_autovalida();

CREATE FUNCTION fn_cuestionario_no_autovalida()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_parte char(1);
BEGIN
    SELECT parte
    INTO v_parte
    FROM pregunta
    WHERE id_pregunta = NEW.id_pregunta;

    IF v_parte = 'B'
       AND NEW.id_personal IS NOT NULL
       AND NEW.id_personal = NEW.id_donante THEN
        RAISE EXCEPTION 'El personal no puede validar su propia donacion';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_cuestionario_no_autovalida
BEFORE INSERT OR UPDATE ON cuestionario
FOR EACH ROW
EXECUTE FUNCTION fn_cuestionario_no_autovalida();

CREATE FUNCTION fn_extraccion_no_autovalida()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM cita
        WHERE id_cita = NEW.id_cita
          AND id_usuario = NEW.id_personal
    ) THEN
        RAISE EXCEPTION 'El personal no puede validar su propia donacion';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_extraccion_no_autovalida
BEFORE INSERT OR UPDATE ON extraccion
FOR EACH ROW
EXECUTE FUNCTION fn_extraccion_no_autovalida();

-- RN03.
CREATE FUNCTION fn_cita_solicitud_propia()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.id_solicitud IS NOT NULL AND EXISTS (
        SELECT 1
        FROM solicitud
        WHERE id_solicitud = NEW.id_solicitud
          AND id_solicitante = NEW.id_usuario
    ) THEN
        RAISE EXCEPTION 'Un usuario no puede citarse por una solicitud propia';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_cita_solicitud_propia
BEFORE INSERT OR UPDATE ON cita
FOR EACH ROW
EXECUTE FUNCTION fn_cita_solicitud_propia();

-- RN10.
CREATE FUNCTION fn_extraccion_si_apto()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM medicion
        WHERE id_cita = NEW.id_cita
          AND apto = false
    ) THEN
        RAISE EXCEPTION 'No se registra la extraccion si hay una medicion no apta';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_extraccion_si_apto
BEFORE INSERT OR UPDATE ON extraccion
FOR EACH ROW
EXECUTE FUNCTION fn_extraccion_si_apto();

-- fecha_fin = fecha_inicio + dias_rehabilitacion; nula si el diferimiento es permanente.
CREATE FUNCTION fn_registro_fecha_fin()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_tipo varchar(20);
    v_dias integer;
BEGIN
    SELECT tipo, dias_rehabilitacion
    INTO v_tipo, v_dias
    FROM diferimiento
    WHERE id_diferimiento = NEW.id_diferimiento;

    IF NOT FOUND THEN
        RETURN NEW;
    END IF;

    IF v_tipo = 'Permanente' THEN
        NEW.fecha_fin := NULL;
    ELSIF NEW.fecha_fin IS NULL AND v_dias IS NOT NULL THEN
        NEW.fecha_fin := NEW.fecha_inicio + v_dias;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_registro_fecha_fin
BEFORE INSERT OR UPDATE ON registro_diferimiento
FOR EACH ROW
EXECUTE FUNCTION fn_registro_fecha_fin();

-- RN12: la bitacora de la unidad no se actualiza ni se borra.
CREATE FUNCTION fn_no_modificar_ni_borrar()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% no se actualiza ni se elimina', TG_TABLE_NAME;
END;
$$;

CREATE TRIGGER trg_transicion_estado_inmutable
BEFORE UPDATE OR DELETE ON transicion_estado
FOR EACH ROW
EXECUTE FUNCTION fn_no_modificar_ni_borrar();

-- La auditoria no se elimina.
CREATE FUNCTION fn_no_borrar()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% no se elimina', TG_TABLE_NAME;
END;
$$;

CREATE TRIGGER trg_auditoria_no_borrar
BEFORE DELETE ON auditoria
FOR EACH ROW
EXECUTE FUNCTION fn_no_borrar();

COMMIT;
